// Generated by Apple Swift version 3.0 (swiftlang-800.0.46.2 clang-800.0.38)
#pragma clang diagnostic push

#if defined(__has_include) && __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if defined(__has_include) && __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if defined(__has_attribute) && __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if defined(__has_attribute) && __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if defined(__has_attribute) && __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_EXTRA _name : _type
# if defined(__has_feature) && __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) SWIFT_ENUM(_type, _name)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if defined(__has_feature) && __has_feature(modules)
@import ObjectiveC;
@import Foundation;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"

SWIFT_CLASS("_TtC9AcceptSDK28AcceptSDKCardFieldsValidator")
@interface AcceptSDKCardFieldsValidator : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (NSInteger)cardExpirationYearMin;
- (BOOL)validateSecurityCodeWithString:(NSString * _Nonnull)inSecurityCode;
- (BOOL)validateCardWithLuhnAlgorithm:(NSString * _Nonnull)inCardNumber;
- (BOOL)validateExpirationDate:(NSString * _Nonnull)inMonth inYear:(NSString * _Nonnull)inYear;
@end

typedef SWIFT_ENUM(NSInteger, AcceptSDKEnvironment) {
  AcceptSDKEnvironmentENV_LIVE = 0,
  AcceptSDKEnvironmentENV_TEST = 1,
};

@class Messages;

SWIFT_CLASS("_TtC9AcceptSDK22AcceptSDKErrorResponse")
@interface AcceptSDKErrorResponse : NSObject
- (Messages * _Nonnull)getMessages;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class AcceptSDKRequest;
@class AcceptSDKTokenResponse;

SWIFT_CLASS("_TtC9AcceptSDK16AcceptSDKHandler")
@interface AcceptSDKHandler : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithEnvironment:(enum AcceptSDKEnvironment)environment OBJC_DESIGNATED_INITIALIZER;
- (void)getTokenWithRequest:(AcceptSDKRequest * _Nonnull)inRequest successHandler:(void (^ _Nonnull)(AcceptSDKTokenResponse * _Nonnull))successHandler failureHandler:(void (^ _Nonnull)(AcceptSDKErrorResponse * _Nonnull))failureHandler;
@end

@class MerchantAuthenticaton;
@class SecurePaymentContainerRequest;

SWIFT_CLASS("_TtC9AcceptSDK16AcceptSDKRequest")
@interface AcceptSDKRequest : NSObject
@property (nonatomic, strong) MerchantAuthenticaton * _Nonnull merchantAuthentication;
@property (nonatomic, strong) SecurePaymentContainerRequest * _Nonnull securePaymentContainerRequest;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC9AcceptSDK17AcceptSDKSettings")
@interface AcceptSDKSettings : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class OpaqueData;

SWIFT_CLASS("_TtC9AcceptSDK22AcceptSDKTokenResponse")
@interface AcceptSDKTokenResponse : NSObject
- (OpaqueData * _Nonnull)getOpaqueData;
- (Messages * _Nonnull)getMessages;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC9AcceptSDK11FingerPrint")
@interface FingerPrint : NSObject
@property (nonatomic, copy) NSString * _Nonnull fingerPrintHashValue;
@property (nonatomic, copy) NSString * _Nonnull sequence;
@property (nonatomic, copy) NSString * _Nonnull timestamp;
@property (nonatomic, copy) NSString * _Nullable currencyCode;
@property (nonatomic, copy) NSString * _Nonnull amount;
- (nullable instancetype)initInHashValue:(NSString * _Nonnull)inHashValue inSequence:(NSString * _Nonnull)inSequence inTimestamp:(NSString * _Nonnull)inTimestamp inCurrencyCode:(NSString * _Nullable)inCurrencyCode inAmount:(NSString * _Nullable)inAmount OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC9AcceptSDK21MerchantAuthenticaton")
@interface MerchantAuthenticaton : NSObject
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic, strong) FingerPrint * _Nullable fingerPrint;
@property (nonatomic, copy) NSString * _Nullable clientKey;
@property (nonatomic, copy) NSString * _Nullable mobileDeviceId;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC9AcceptSDK7Message")
@interface Message : NSObject
- (NSString * _Nonnull)getCode;
- (NSString * _Nonnull)getText;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC9AcceptSDK8Messages")
@interface Messages : NSObject
- (NSString * _Nonnull)getResultCode;
- (NSArray<Message *> * _Nonnull)getMessages;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface NSMutableURLRequest (SWIFT_EXTENSION(AcceptSDK))
@end


SWIFT_CLASS("_TtC9AcceptSDK10OpaqueData")
@interface OpaqueData : NSObject
- (NSString * _Nonnull)getDataDescriptor;
- (NSString * _Nonnull)getDataValue;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class WebCheckOutDataType;

SWIFT_CLASS("_TtC9AcceptSDK29SecurePaymentContainerRequest")
@interface SecurePaymentContainerRequest : NSObject
@property (nonatomic, strong) WebCheckOutDataType * _Nonnull webCheckOutDataType;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC9AcceptSDK5Token")
@interface Token : NSObject
@property (nonatomic, copy) NSString * _Nonnull cardNumber;
@property (nonatomic, copy) NSString * _Nonnull expirationMonth;
@property (nonatomic, copy) NSString * _Nonnull expirationYear;
@property (nonatomic, copy) NSString * _Nullable cardCode;
@property (nonatomic, copy) NSString * _Nullable zip;
@property (nonatomic, copy) NSString * _Nullable fullName;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC9AcceptSDK19WebCheckOutDataType")
@interface WebCheckOutDataType : NSObject
@property (nonatomic, strong) Token * _Nonnull token;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

#pragma clang diagnostic pop
